import {Link,router,useForm,usePage} from '@inertiajs/react';
import {useState} from 'react';
import AppLayout from '@/Layouts/AppLayout';
import PageHeader from '@/Components/App/PageHeader';
import FormField from '@/Components/Forms/FormField';
import MoneyDisplay from '@/Components/Finance/MoneyDisplay';
import ConfirmDialog from '@/Components/Feedback/ConfirmDialog';
import {EmptyState} from '@/Components/Feedback/States';
import type {Review} from '@/types/ticketing';
export default function Create({assignments,revenue_heads,filters,review}:{assignments:{id:number;label:string}[];revenue_heads:{id:number;name:string}[];filters:Record<string,string>;review:Review|null}) {
    const errors=usePage().props.errors;
    const [lookup,setLookup]=useState(filters.lookup??''); const [assignment,setAssignment]=useState(String(filters.assignment_id??'')); const [head,setHead]=useState(String(filters.revenue_head_id??''));
    const [confirm,setConfirm]=useState(false); const [busy,setBusy]=useState(false);
    const form=useForm({assignment_id:review?.assignment_id??0,revenue_head_id:review?.revenue_head_id??0,confirmation:review?.confirmation??'',request_key:review?.request_key??''});
    const current=review&&String(review.assignment_id)===assignment&&String(review.revenue_head_id)===head;
    const context=review?.context_snapshot;
    function resolve(searchOnly=false) {router.get('/tickets/create',searchOnly?{lookup}:{lookup,assignment_id:assignment,revenue_head_id:head},{preserveState:false,onStart:()=>setBusy(true),onFinish:()=>setBusy(false)});}
    return <AppLayout title="Issue ticket" breadcrumbs={[{label:'Tickets',href:'/tickets'},{label:'Issue ticket'}]}><PageHeader title="Issue ticket" eyebrow="TICKETING" description="Find an active assignment, select the revenue head, then review the fee returned by the server."/>
    <>{Object.values(errors).length>0&&<div className="notice field-error" role="alert">{Object.entries(errors).map(([key,message])=><p key={key}>{message}</p>)}</div>}</><section className="panel"><div className="panel-header"><h2>1. Find the operating assignment</h2></div><form className="filter-bar" onSubmit={e=>{e.preventDefault();resolve(true);}}><FormField id="assignment-search" label="Find vehicle, driver or operator" hint="Showing up to 50 current assignments. Search to narrow the list."><input id="assignment-search" maxLength={190} value={lookup} onChange={e=>setLookup(e.target.value)}/></FormField><button className="button secondary" disabled={busy}>Search assignments</button></form>
    <form className="panel-body" onSubmit={e=>{e.preventDefault();resolve();}}><div className="form-grid"><FormField id="assignment_id" label="Active assignment" error={form.errors.assignment_id}><select id="assignment_id" required value={assignment} onChange={e=>setAssignment(e.target.value)}><option value="">Select an assignment</option>{assignments.map(a=><option key={a.id} value={a.id}>{a.label}</option>)}</select></FormField><FormField id="revenue_head_id" label="Revenue head" error={form.errors.revenue_head_id}><select id="revenue_head_id" required value={head} onChange={e=>setHead(e.target.value)}><option value="">Select a revenue head</option>{revenue_heads.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select></FormField></div><div className="form-actions"><button className="button secondary" disabled={busy}>Review applicable fee</button></div></form>{!assignments.length&&<EmptyState title="No current assignments found" description="Try another search or ask an administrator to create an active assignment within your managed park."/>}</section>
    {current&&context&&<section className="panel ticket-review"><div className="panel-header"><h2>2. Review and issue</h2></div><div className="panel-body"><div className="ticket-total"><span className="eyebrow">{review.fee_code_snapshot} · {review.fee_name_snapshot}</span><strong><MoneyDisplay amount={review.amount} currency={review.currency}/></strong></div><dl className="detail-list">{[['Driver',context.driver.name],['Vehicle',context.vehicle.registration],['Operator',context.operator.name],['Park',context.park.name],['LGA',context.lga.name],['Route',context.route?context.route.origin+' → '+context.route.destination:'No route'],['Validity',review.expiry_minutes?review.expiry_minutes+' minutes from issuance':'No expiry configured']].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="notice">The server rechecks this assignment and fee when you issue. The ticket starts unpaid; payment processing is not enabled yet.</p>{form.errors.confirmation&&<p className="field-error" role="alert">{form.errors.confirmation}</p>}<div className="form-actions"><Link className="button secondary" href="/tickets">Back to tickets</Link><button className="button" disabled={form.processing} onClick={()=>setConfirm(true)}>Issue reviewed ticket</button></div></div></section>}
    <ConfirmDialog open={confirm} title="Issue this ticket?" description="Create an unpaid ticket with the reviewed amount and operating context. This action records an obligation and does not collect money." onClose={()=>setConfirm(false)} onConfirm={()=>{setConfirm(false);form.post('/tickets');}}/>
    </AppLayout>;
}
