import {useForm} from '@inertiajs/react';
import {useState} from 'react';
import RecordDetail from '@/Components/Incidents/RecordDetail';
import FormField from '@/Components/Forms/FormField';
import ConfirmDialog from '@/Components/Feedback/ConfirmDialog';
import useFieldOnline from '@/hooks/useFieldOnline';
import type {OperationalRecord} from '@/types/incidents';
function ViolationForm({record,idempotency_key}:{record:OperationalRecord;idempotency_key:string}){const online=useFieldOnline(),[confirm,setConfirm]=useState(false),f=useForm({category:'',description:'',idempotency_key});return <><h2>Record violation observation</h2><p className="muted small">Describe the observed issue. Categories do not define statutory offences or fees.</p><form className="payment-form" onSubmit={e=>{e.preventDefault();if(online&&!f.processing)setConfirm(true);}}><FormField id="violation-category" label="Category" error={f.errors.category}><input id="violation-category" required minLength={2} maxLength={80} value={f.data.category} onChange={e=>f.setData('category',e.target.value)}/></FormField><FormField id="violation-description" label="Description" error={f.errors.description}><textarea id="violation-description" required minLength={10} maxLength={4000} rows={4} value={f.data.description} onChange={e=>f.setData('description',e.target.value)}/></FormField>{f.errors.idempotency_key&&<p role="alert">{f.errors.idempotency_key}</p>}<button className="button" disabled={!online||f.processing}>{f.processing?'Saving…':'Review violation observation'}</button></form><ConfirmDialog open={confirm} title="Confirm violation observation" description="Retain this observation against the inspection and its original operating context?" onClose={()=>setConfirm(false)} onConfirm={()=>{setConfirm(false);f.post('/inspections/'+record.public_id+'/violations',{preserveScroll:true});}}/></>;}
export default function Show({record,can_record_violation,idempotency_key}:{record:OperationalRecord;can_record_violation:boolean;idempotency_key:string}){return <RecordDetail record={record} kind="inspections" idempotency_key={idempotency_key}>{can_record_violation&&<ViolationForm key={idempotency_key} record={record} idempotency_key={idempotency_key}/>}</RecordDetail>;}
