import {Link,useForm,router} from '@inertiajs/react';
import {useState} from 'react';
import AppLayout from '@/Layouts/AppLayout';
import PageHeader from '@/Components/App/PageHeader';
import FormField from '@/Components/Forms/FormField';
import {optionName,type Options} from '@/types/catalog';
export default function Create({options,lookup}:{options:Options;lookup:string}) {
 const form=useForm({driver_id:'',vehicle_id:'',operator_id:'',park_id:'',route_id:'',starts_at:new Date().toISOString().slice(0,19),is_primary:true}); const [search,setSearch]=useState(lookup);
 const [previous,setPrevious]=useState(options); const [cached,setCached]=useState(options);
 if(options!==previous){setPrevious(options);setCached(Object.fromEntries(Object.entries(options).map(([k,v])=>[k,[...(cached[k]??[]),...v.filter(o=>!cached[k]?.some(c=>c.id===o.id))]])));}
 return <AppLayout title="Create assignment" breadcrumbs={[{label:'Assignments',href:'/assignments'},{label:'Create assignment'}]}><PageHeader title="Create assignment" description="The server validates active participants and park / operator route approvals. End an existing primary assignment first."/><form className="panel filter-bar" onSubmit={e=>{e.preventDefault();router.get('/assignments/create',{lookup:search},{preserveState:true,preserveScroll:true});}}><FormField id="lookup" label="Find assignment participants" hint="Options are limited to 100 results. Search by name, reference, registration or route."><input id="lookup" value={search} maxLength={190} onChange={e=>setSearch(e.target.value)}/></FormField><button className="button secondary">Search options</button></form><form className="panel form-panel" onSubmit={e=>{e.preventDefault();form.post('/assignments');}}><div className="panel-body"><div className="form-grid">{(['driver','vehicle','operator','park','route'] as const).map(key=>{const field=(key+'_id') as 'driver_id'|'vehicle_id'|'operator_id'|'park_id'|'route_id';const selected=cached[key+'s']?.filter(o=>String(o.id)===form.data[field])??[];const list=[...options[key+'s'],...selected.filter(o=>!options[key+'s'].some(v=>v.id===o.id))];return <FormField key={key} id={field} label={key[0].toUpperCase()+key.slice(1)} error={form.errors[field]}><select id={field} required={key!=='route'} value={form.data[field]} onChange={e=>form.setData(field,e.target.value)}><option value="">{key==='route'?'No route':'Select '+key}</option>{list.map(o=><option key={o.id} value={o.id}>{optionName(o)}</option>)}</select></FormField>;})}<FormField id="starts_at" label="Starts at (UTC)" error={form.errors.starts_at}><input id="starts_at" required type="datetime-local" step="1" value={form.data.starts_at} onChange={e=>form.setData('starts_at',e.target.value)}/></FormField></div><label className="checkbox-label"><input type="checkbox" checked={form.data.is_primary} onChange={e=>form.setData('is_primary',e.target.checked)}/>Primary assignment</label><div className="form-actions"><Link className="button secondary" href="/assignments">Cancel</Link><button className="button" disabled={form.processing}>Create assignment</button></div></div></form></AppLayout>;
}
