import {useForm} from '@inertiajs/react';
import {useState} from 'react';
import FormField from '@/Components/Forms/FormField';
import ConfirmDialog from '@/Components/Feedback/ConfirmDialog';
import useFieldOnline from '@/hooks/useFieldOnline';
import type {Choice,Complaint} from '@/types/complaints';
export default function ManageForm({record,transitions,assignees,idempotency_key}:{record:Complaint;transitions:string[];assignees:Choice[];idempotency_key:string}){
 const online=useFieldOnline(),[confirm,setConfirm]=useState(false);
 const f=useForm({action:transitions.length?'status':assignees.length?'assign':'note',status:transitions[0]??'',assignee:'',reason:'',resolution:'',note:'',is_internal:true,expected_status:record.status,expected_assignee:record.assignee?.public_id??null,idempotency_key});
 return <section className="panel"><div className="panel-header"><h2>Help Desk review</h2></div><div className="panel-body"><form className="payment-form" onSubmit={e=>{e.preventDefault();if(online&&!f.processing)setConfirm(true);}}>
 <FormField id="complaint-action" label="Action" error={f.errors.action}><select id="complaint-action" value={f.data.action} onChange={e=>f.setData('action',e.target.value)}>{transitions.length>0&&<option value="status">Update status</option>}{assignees.length>0&&<option value="assign">Assign officer</option>}<option value="note">Add note</option></select></FormField>
 {f.data.action==='status'&&<FormField id="next-status" label="Next status" error={f.errors.status}><select id="next-status" value={f.data.status} onChange={e=>f.setData('status',e.target.value)}>{transitions.map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></FormField>}
 {f.data.action==='assign'&&<FormField id="complaint-assignee" label="Assigned officer" error={f.errors.assignee}><select id="complaint-assignee" required value={f.data.assignee} onChange={e=>f.setData('assignee',e.target.value)}><option value="">Choose an officer</option>{assignees.map(a=><option key={a.public_id} value={a.public_id}>{a.name}</option>)}</select></FormField>}
 {f.data.action!=='note'&&<FormField id="complaint-reason" label="Reason" error={f.errors.reason}><textarea id="complaint-reason" required minLength={10} maxLength={4000} rows={3} value={f.data.reason} onChange={e=>f.setData('reason',e.target.value)}/></FormField>}
 {f.data.action==='status'&&f.data.status==='resolved'&&<FormField id="complaint-resolution" label="Resolution" error={f.errors.resolution}><textarea id="complaint-resolution" required minLength={10} maxLength={4000} rows={4} value={f.data.resolution} onChange={e=>f.setData('resolution',e.target.value)}/></FormField>}
 {f.data.action==='note'&&<><FormField id="complaint-note" label="Note" error={f.errors.note}><textarea id="complaint-note" required minLength={2} maxLength={4000} rows={4} value={f.data.note} onChange={e=>f.setData('note',e.target.value)}/></FormField><label className="checkbox-label"><input type="checkbox" checked={f.data.is_internal} onChange={e=>f.setData('is_internal',e.target.checked)}/> Internal staff note</label><p className="muted small">Shared notes can be read by authorized viewers of this complaint, including its operator. They are not published on the public form.</p></>}
 {f.errors.expected_status&&<p role="alert">{f.errors.expected_status}</p>}{f.errors.idempotency_key&&<p role="alert">{f.errors.idempotency_key}</p>}<button className="button" disabled={!online||f.processing}>{f.processing?'Saving…':'Review and save action'}</button>
 </form></div><ConfirmDialog open={confirm} title="Confirm complaint review" description="Record this decision with your identity and timestamp? Complaint history is retained." onClose={()=>setConfirm(false)} onConfirm={()=>{setConfirm(false);if(online&&!f.processing){f.transform(d=>{const data:Record<string,unknown>={...d};if(d.action!=='status')delete data.status;if(d.action!=='assign')delete data.assignee;if(d.action!=='note'){delete data.note;delete data.is_internal;}if(d.action!=='status'||d.status!=='resolved')delete data.resolution;if(d.action==='note')delete data.reason;return data;});f.post('/complaints/'+record.public_id+'/manage',{preserveScroll:true});}}}/></section>;
}
