import {Link,useForm} from '@inertiajs/react';
import FinanceListControls from '@/Components/Finance/FinanceListControls';
import AppLayout from '@/Layouts/AppLayout';
import PageHeader from '@/Components/App/PageHeader';
import StatusBadge from '@/Components/Data/StatusBadge';
import Pagination from '@/Components/Data/Pagination';
import FormField from '@/Components/Forms/FormField';
import {EmptyState} from '@/Components/Feedback/States';
import {dateTime} from '@/lib/formatters';
import type {Paginated} from '@/types';
import {label,type Run} from '@/types/reconciliation';
export default function Index({records,can_start,filters,statewide}:{records:Paginated<Run>;can_start:boolean;filters:{search?:string;status?:string;from?:string;to?:string;sort?:string;order?:string};statewide:boolean}){const form=useForm({from:filters.from??'',to:filters.to??'',sort:filters.sort??'started_at',order:filters.order??'desc',search:filters.search??'',status:filters.status??''});return <AppLayout title="Reconciliation runs" breadcrumbs={[{label:'Reconciliation',href:'/finance/reconciliation'},{label:'Runs'}]}><PageHeader title="Reconciliation runs" description="Repeatable matching with retained findings and audited reviews." actions={can_start&&<Link className="button" href="/finance/reconciliation/runs/create">Start reconciliation</Link>}/><form className="filter-bar" onSubmit={e=>{e.preventDefault();form.get('/finance/reconciliation/runs');}}><FormField id="run-search" label="Run reference"><input id="run-search" maxLength={190} value={form.data.search} onChange={e=>form.setData('search',e.target.value)}/></FormField>{statewide&&<FormField id="run-status" label="Status"><select id="run-status" value={form.data.status} onChange={e=>form.setData('status',e.target.value)}><option value="">All statuses</option>{['queued','running','completed','completed_with_exceptions','failed'].map(s=><option value={s} key={s}>{label(s)}</option>)}</select></FormField>}<FinanceListControls values={form.data} onChange={(key,value)=>form.setData(key,value)} sorts={[['started_at','Run started date'],['period_start','Period start'],['reconciliation_reference','Reference']]} dateLabel="Run started" errors={form.errors}/><button className="button" disabled={form.processing}>{form.processing?'Applying…':'Apply filters'}</button><Link className="button secondary" href="/finance/reconciliation/runs">Reset</Link></form><section className="panel">{records.data.length?<div className="table-scroll" tabIndex={0} role="region" aria-label="Reconciliation runs"><table><thead><tr>{['Reference','Period start','Period end (exclusive)','Status','Findings','Open exceptions'].map(s=><th scope="col" key={s}>{s}</th>)}</tr></thead><tbody>{records.data.map(r=><tr key={r.public_id}><td><Link className="text-link" href={'/finance/reconciliation/runs/'+r.public_id}>{r.reconciliation_reference}</Link></td><td>{dateTime(r.period_start)}</td><td>{dateTime(r.period_end)}</td><td><StatusBadge status={r.status}/></td><td>{r.summary.total}</td><td>{r.summary.open}</td></tr>)}</tbody></table></div>:<EmptyState title="No reconciliation runs yet" description="Finance staff can start a run for a selected period and location."/>}<Pagination page={records}/></section></AppLayout>;}
