import {Link,useForm} from '@inertiajs/react';
import {useState} from 'react';
import AppLayout from '@/Layouts/AppLayout';
import PageHeader from '@/Components/App/PageHeader';
import FormField from '@/Components/Forms/FormField';
import ConfirmDialog from '@/Components/Feedback/ConfirmDialog';
import MoneyDisplay from '@/Components/Finance/MoneyDisplay';
export type Props={source:{public_id:string;payment_reference?:string;transaction_reference?:string;amount:string;currency:string}|null;idempotency_key:string};
export default function CorrectionForm({source,idempotency_key,refund}:Props&{refund:boolean}) {
 const form=useForm({original_transaction:source?.public_id??'',amount:'',adjustment_type:'debit',reason:'',idempotency_key});const [confirm,setConfirm]=useState(false);const title=refund?'Request refund':'Request adjustment';const base=refund?'/finance/refunds':'/finance/adjustments';
 return <AppLayout title={title} breadcrumbs={[{label:refund?'Refunds':'Adjustments',href:base},{label:title}]}><PageHeader title={title} description="Enter the correction amount and reason. A different authorized finance user must approve it."/>{refund&&<p className="notice demo-payment-banner"><strong>DEMO REFUND MODE</strong> — No real money will be sent.</p>}<section className="panel"><div className="panel-body">{source&&<p>Original: <Link className="text-link" href={(refund?'/payments/':'/finance/ledger/')+source.public_id}>{source.payment_reference??source.transaction_reference}</Link> · <MoneyDisplay amount={source.amount} currency={source.currency}/></p>}{!source&&<p className="notice">Choose the original transaction from <Link className="text-link" href="/finance/ledger">the financial ledger</Link>, then select “Request adjustment” on its detail page.</p>}<form className="payment-form" onSubmit={e=>{e.preventDefault();setConfirm(true);}}>{!refund&&<><FormField id="adjustment-type" label="Correction direction" error={form.errors.adjustment_type}><select id="adjustment-type" value={form.data.adjustment_type} onChange={e=>form.setData('adjustment_type',e.target.value)}><option value="debit">Debit — reduce balance</option><option value="credit">Credit — increase balance</option></select></FormField></>}<FormField id="correction-amount" label={'Amount ('+(source?.currency??'source currency')+')'} error={form.errors.amount}><input id="correction-amount" inputMode="decimal" required maxLength={16} pattern="[0-9]+(\.[0-9]{1,2})?" value={form.data.amount} onChange={e=>form.setData('amount',e.target.value)}/></FormField><FormField id="correction-reason" label="Request reason" error={form.errors.reason}><textarea id="correction-reason" required minLength={10} maxLength={2000} value={form.data.reason} onChange={e=>form.setData('reason',e.target.value)}/></FormField>{form.errors.original_transaction&&<p className="field-error" role="alert">{form.errors.original_transaction}</p>}{form.errors.idempotency_key&&<p className="field-error" role="alert">{form.errors.idempotency_key}</p>}<p className="muted small">Amounts are checked against retained entries and pending requests. The original financial record remains unchanged.</p><button className="button" disabled={form.processing||!source}>{form.processing?'Submitting…':title}</button></form><ConfirmDialog open={confirm} title={'Submit this '+(refund?'refund':'adjustment')+' request?'} description="The amount and request reason will be retained for independent review. This request alone does not move funds." onClose={()=>setConfirm(false)} onConfirm={()=>{setConfirm(false);form.post(refund?'/payments/'+source?.public_id+'/refund':base);}}/></div></section></AppLayout>;
}
