import {Link,useForm} from '@inertiajs/react';
import {useState} from 'react';
import AppLayout from '@/Layouts/AppLayout';
import PageHeader from '@/Components/App/PageHeader';
import FormField from '@/Components/Forms/FormField';
import ConfirmDialog from '@/Components/Feedback/ConfirmDialog';
import MoneyDisplay from '@/Components/Finance/MoneyDisplay';
import StatusBadge from '@/Components/Data/StatusBadge';
import Pagination from '@/Components/Data/Pagination';
import {dateTime} from '@/lib/formatters';
import type {CorrectionDetail as Props} from '@/types/corrections';
function Actions({record,can_review,can_process,idempotency_key,refund}:Props&{refund:boolean}) {
 const form=useForm({decision:'approved',scenario:'successful',reason:'',idempotency_key}); const [confirm,setConfirm]=useState(false);
 if(!can_review&&!can_process)return null;
 return <section className="panel"><div className="panel-body"><h2>{can_review?'Independent review':'Process demo refund'}</h2><p className="muted">{can_review?'The requester cannot approve their own request. A decision and reason are retained.':'Only a successful outcome creates a debit. Failed outcomes may be retried after checking the available balance.'}</p><form className="payment-form" onSubmit={e=>{e.preventDefault();setConfirm(true);}}>{can_review?<FormField id="review-decision" label="Decision" error={form.errors.decision}><select id="review-decision" value={form.data.decision} onChange={e=>form.setData('decision',e.target.value)}><option value="approved">Approve</option><option value="rejected">Reject</option></select></FormField>:<FormField id="refund-scenario" label="Demo refund outcome" error={form.errors.scenario}><select id="refund-scenario" value={form.data.scenario} onChange={e=>form.setData('scenario',e.target.value)}>{['successful','failed','processing'].map(s=><option key={s}>{s}</option>)}</select></FormField>}<FormField id="review-reason" label="Decision reason" error={form.errors.reason}><textarea id="review-reason" required minLength={10} maxLength={2000} value={form.data.reason} onChange={e=>form.setData('reason',e.target.value)}/></FormField>{Object.entries(form.errors).filter(([k])=>!['decision','reason','scenario'].includes(k)).map(([k,v])=><p className="field-error" role="alert" key={k}>{v}</p>)}<button className="button" disabled={form.processing}>{form.processing?'Recording…':can_review?'Record review':'Record demo refund outcome'}</button></form><ConfirmDialog open={confirm} title={can_review?'Record this review?':'Record this demo refund outcome?'} description={can_review?'This financial decision and your reason will remain in history. Approved adjustments add a new ledger entry.':'No real money is transferred. A successful refund adds a linked debit and invalidates ticket and receipt verification.'} onClose={()=>setConfirm(false)} onConfirm={()=>{setConfirm(false);form.post('/finance/'+(refund?'refunds':'adjustments')+'/'+record.public_id+(can_review?'/review':'/process'));}}/></div></section>;
}
export default function CorrectionDetail(props:Props&{refund:boolean}) {
 const {record:r,source,ledger_url,history,refund}=props;const base=refund?'/finance/refunds':'/finance/adjustments';
 return <AppLayout title={r.reference} breadcrumbs={[{label:refund?'Refunds':'Adjustments',href:base},{label:r.reference}]}><PageHeader title={r.reference} description={refund?'Refund request and retained processing history.':'Adjustment request linked to its original ledger record.'}/>{refund&&<p className="notice demo-payment-banner"><strong>DEMO REFUND MODE</strong> — Simulated funds only.</p>}<section className="panel"><div className="panel-body"><div className="ticket-total"><strong><MoneyDisplay amount={r.amount} currency={r.currency}/></strong><StatusBadge status={r.status}/></div><dl className="detail-list"><div><dt>Original record</dt><dd>{source.url?<Link className="text-link" href={source.url}>{source.reference}</Link>:source.reference}</dd></div>{[['Direction',r.direction],['Request reason',r.reason],['Requested at',dateTime(r.requested_at)],...(refund?[['Processed at',r.processed_at?dateTime(r.processed_at):'—'],['Provider reference',r.provider_reference??'—']]:[['Approved at',r.approved_at?dateTime(r.approved_at):'—']])].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{ledger_url&&<Link className="button secondary" href={ledger_url}>View correction ledger entry</Link>}</div></section><Actions key={props.idempotency_key} {...props}/><section className="panel"><div className="panel-header"><h2>Financial audit history</h2></div><div className="table-scroll" tabIndex={0} role="region" aria-label="Financial audit history"><table><thead><tr>{['Event','Actor','Reason','Recorded at'].map(s=><th scope="col" key={s}>{s}</th>)}</tr></thead><tbody>{history.data.map(h=><tr key={h.id}><td>{h.event}</td><td>{h.actor}</td><td>{h.reason}</td><td>{dateTime(h.occurred_at)}</td></tr>)}</tbody></table></div><Pagination page={history}/></section></AppLayout>;
}
