import {Link,router,usePage} from '@inertiajs/react';
import {useState} from 'react';
import AppLayout from '@/Layouts/AppLayout';
import PageHeader from '@/Components/App/PageHeader';
import FormField from '@/Components/Forms/FormField';
import FinancialTable from './FinancialTable';
import type {FinancialPage} from '@/types/payments';
type Option={id:number;name:string};
export default function FinancialList({records,filters,ledger=false,parks=[],lgas=[],revenue_heads=[]}:{records:FinancialPage;filters:Record<string,string>;ledger?:boolean;parks?:Option[];lgas?:Option[];revenue_heads?:Option[]}) {
 const [values,setValues]=useState(filters);const [loading,setLoading]=useState(false);const errors=usePage().props.errors;const path=ledger?'/finance/ledger':'/payments';
 const apply=(extra:Record<string,string>={})=>router.get(path,{...values,...extra},{preserveState:true,replace:true,onStart:()=>setLoading(true),onFinish:()=>setLoading(false)});
 const lists=ledger?[['direction','Direction',['credit','debit']],['transaction_type','Transaction type',['payment','reversal','refund','adjustment']]]:[['status','Payment status',['pending','successful','failed','reversed','refunded']],['channel','Channel',['cashless_pos','transfer','ussd','gateway','demo','other']]];
 return <AppLayout title={ledger?'Financial ledger':'Payments'} breadcrumbs={[{label:'Finance'},{label:ledger?'Ledger':'Payments'}]}><PageHeader title={ledger?'Financial ledger':'Payments'} description={ledger?'Immutable credits and debits. Original entries are retained; corrections add new entries.':'Payment attempts within your access. Demo payments never move real funds.'}/>{Object.values(errors).length>0&&<div className="notice field-error" role="alert">{Object.entries(errors).map(([k,v])=><p key={k}>{v}</p>)}</div>}<section className="panel"><form className="filter-bar" onSubmit={e=>{e.preventDefault();apply({page:'1'});}}><FormField id="financial-search" label={ledger?'Search ledger':'Search payments'}><input id="financial-search" value={values.search??''} maxLength={190} placeholder="Reference, ticket or vehicle" onChange={e=>setValues({...values,search:e.target.value})}/></FormField>{lists.map(([key,label,list])=><FormField key={String(key)} id={String(key)} label={String(label)}><select id={String(key)} value={values[String(key)]??''} onChange={e=>setValues({...values,[String(key)]:e.target.value})}><option value="">All</option>{(list as string[]).map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></FormField>)}{([['lga_id','LGA',lgas],['park_id','Park',parks],['revenue_head_id','Revenue head',revenue_heads]] as const).map(([key,label,list])=><FormField key={key} id={key} label={label}><select id={key} value={values[key]??''} onChange={e=>setValues({...values,[key]:e.target.value})}><option value="">All accessible records</option>{list.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></FormField>)}{(['from','to'] as const).map(key=><FormField key={key} id={key} label={(key==='from'?'From':'To')+' (UTC date)'}><input id={key} type="date" value={values[key]??''} onChange={e=>setValues({...values,[key]:e.target.value})}/></FormField>)}<button className="button secondary">Apply filters</button><Link className="text-link small" href={path}>Clear</Link></form><FinancialTable records={records} ledger={ledger} loading={loading} sort={filters.sort} order={filters.order} onSort={column=>apply({sort:column,order:filters.sort===column&&filters.order==='asc'?'desc':'asc'})}/></section></AppLayout>;
}
