import {Link} from '@inertiajs/react';
import AppLayout from '@/Layouts/AppLayout';
import PageHeader from '@/Components/App/PageHeader';
import MoneyDisplay from '@/Components/Finance/MoneyDisplay';
import StatusBadge from '@/Components/Data/StatusBadge';
import {dateTime} from '@/lib/formatters';
import type {FinancialRow} from '@/types/payments';
type Props={transaction:FinancialRow&{description:string|null;source:string};ticket:{public_id:string;ticket_reference:string}|null;payment:{public_id:string;payment_reference:string}|null;parent:{public_id:string;transaction_reference:string}|null;reason:string|null;reconciliation:string};
export default function Show({transaction:t,ticket,payment,parent,reason,reconciliation}:Props){return <AppLayout title={t.transaction_reference??'Ledger entry'} breadcrumbs={[{label:'Ledger',href:'/finance/ledger'},{label:t.transaction_reference??'Entry'}]}><PageHeader title={t.transaction_reference??'Ledger entry'} description="Immutable financial entry. Corrections are recorded as additional entries."/><section className="panel"><div className="panel-body"><div className="ticket-total"><strong><MoneyDisplay amount={t.amount} currency={t.currency}/></strong><StatusBadge status={t.direction??''}/></div><dl className="detail-list">{[['Type',t.transaction_type],['Occurred at',dateTime(t.occurred_at)],['Description',t.description],['Source',t.source]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value??'Not recorded'}</dd></div>)}{ticket&&<div><dt>Ticket</dt><dd><Link className="text-link" href={'/tickets/'+ticket.public_id}>{ticket.ticket_reference}</Link></dd></div>}{payment&&<div><dt>Payment</dt><dd><Link className="text-link" href={'/payments/'+payment.public_id}>{payment.payment_reference}</Link></dd></div>}{parent&&<div><dt>Original transaction</dt><dd><Link className="text-link" href={'/finance/ledger/'+parent.public_id}>{parent.transaction_reference}</Link></dd></div>}{reason&&<div><dt>Reason</dt><dd>{reason}</dd></div>}</dl><p className="notice">{reconciliation}</p></div></section></AppLayout>;}
