import {Link} from '@inertiajs/react';
import AppLayout from '@/Layouts/AppLayout';
import PageHeader from '@/Components/App/PageHeader';
import MoneyDisplay from '@/Components/Finance/MoneyDisplay';
import StatusBadge from '@/Components/Data/StatusBadge';
import {dateTime} from '@/lib/formatters';
import type {FinancialRow} from '@/types/payments';
type Props={can_request_adjustment:boolean;adjustments:import('@/types/corrections').Correction[];transaction:FinancialRow&{description:string|null;source:string};ticket:{public_id:string;ticket_reference:string}|null;payment:{public_id:string;payment_reference:string}|null;parent:{public_id:string;transaction_reference:string}|null;reason:string|null;reconciliation:{status:string;exception_type:string|null;url:string|null}|null};
export default function Show({transaction:t,ticket,payment,parent,reason,reconciliation,can_request_adjustment,adjustments}:Props){return <AppLayout title={t.transaction_reference??'Ledger entry'} breadcrumbs={[{label:'Ledger',href:'/finance/ledger'},{label:t.transaction_reference??'Entry'}]}><PageHeader title={t.transaction_reference??'Ledger entry'} description="Immutable financial entry. Corrections are recorded as additional entries."/><section className="panel"><div className="panel-body"><div className="ticket-total"><strong><MoneyDisplay amount={t.amount} currency={t.currency}/></strong><StatusBadge status={t.direction??''}/></div><dl className="detail-list">{[['Type',t.transaction_type],['Occurred at',dateTime(t.occurred_at)],['Description',t.description],['Source',t.source]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value??'Not recorded'}</dd></div>)}{ticket&&<div><dt>Ticket</dt><dd><Link className="text-link" href={'/tickets/'+ticket.public_id}>{ticket.ticket_reference}</Link></dd></div>}{payment&&<div><dt>Payment</dt><dd><Link className="text-link" href={'/payments/'+payment.public_id}>{payment.payment_reference}</Link></dd></div>}{parent&&<div><dt>Original transaction</dt><dd><Link className="text-link" href={'/finance/ledger/'+parent.public_id}>{parent.transaction_reference}</Link></dd></div>}{reason&&<div><dt>Reason</dt><dd>{reason}</dd></div>}</dl><p className="notice">{reconciliation?<>Latest ticket reconciliation: {reconciliation.status.replaceAll('_',' ')}{reconciliation.exception_type&&` · ${reconciliation.exception_type.replaceAll('_',' ')}`}. {reconciliation.url&&<Link className="text-link" href={reconciliation.url}>View finding</Link>}</>:<>Reconciliation access restricted.</>}</p></div></section>{can_request_adjustment&&<p><Link className="button" href={'/finance/adjustments/create?original_transaction='+t.public_id}>Request adjustment</Link></p>}{adjustments.length>0&&<section className="panel"><div className="panel-body"><h2>Adjustment history</h2>{adjustments.map(a=><p key={a.public_id}><Link className="text-link" href={'/finance/adjustments/'+a.public_id}>{a.reference}</Link> · <MoneyDisplay amount={a.amount} currency={a.currency}/> · <StatusBadge status={a.status}/></p>)}</div></section>}</AppLayout>;}
