import {Link} from '@inertiajs/react';
import {useState} from 'react';
import AppLayout from '@/Layouts/AppLayout';
import PageHeader from '@/Components/App/PageHeader';
import DataTable from '@/Components/Data/DataTable';
import StatusBadge from '@/Components/Data/StatusBadge';
import {EmptyState} from '@/Components/Feedback/States';
import AssignmentTable from './AssignmentTable';
import DocumentUploader from './DocumentUploader';
import {catalog,fields,itemName,optionName,type Kind,type Item,type Related} from '@/types/catalog';
import {usePermissions} from '@/hooks/usePermissions';
const tabs:Record<Kind,string[]>={operators:['Overview','Parks','Routes','Drivers','Vehicles','Documents','Tickets','Activity'],drivers:['Overview','Current Assignment','Assignment History','Documents','Tickets','Inspections','Incidents','Activity'],vehicles:['Overview','Current Assignment','Assignment History','Documents','Tickets','Inspections','Incidents','Activity'],'revenue-heads':['Overview','Configurations','Activity'],'fee-configurations':['Overview','Activity']};
export default function CatalogDetail({kind,record,related,can_update,activities}:{kind:Kind;record:Item;related:Related;can_update:boolean;activities:{description:string;created_at:string}[]}) {
 const [tab,setTab]=useState('Overview'); const {can}=usePermissions(); const meta=catalog[kind]; const names=tabs[kind]; const photograph=related.documents?.data.find(d=>d.category==='driver_photo' || d.category==='vehicle_photo');
 return <AppLayout title={itemName(record)} breadcrumbs={[{label:meta.title,href:'/'+kind},{label:itemName(record)}]}><PageHeader title={itemName(record)} eyebrow={meta.singular.toUpperCase()+' PROFILE'} description={record.operator_number??record.driver_number??record.vehicle_number??record.code??record.public_id} actions={can_update && <Link className="button" href={'/'+kind+'/'+record.public_id+'/edit'}>Edit {meta.singular}</Link>}/><div className="scope-strip"><span>Operational status <StatusBadge status={record.status}/></span><span>Registered {record.created_at.slice(0,10)}</span></div>
 <div className="registry-tabs" role="tablist" aria-label="Profile sections" onKeyDown={e=>{if(!['ArrowRight','ArrowLeft','Home','End'].includes(e.key))return;e.preventDefault();const i=e.key==='Home'?0:e.key==='End'?names.length-1:(names.indexOf(tab)+(e.key==='ArrowRight'?1:-1)+names.length)%names.length;setTab(names[i]);document.getElementById('catalog-tab-'+i)?.focus();}}>{names.map((t,i)=><button type="button" role="tab" id={'catalog-tab-'+i} key={t} aria-selected={tab===t} aria-controls="catalog-panel" tabIndex={tab===t?0:-1} onClick={()=>setTab(t)}>{t}</button>)}</div>
 <section className="panel" id="catalog-panel" role="tabpanel" aria-labelledby={'catalog-tab-'+names.indexOf(tab)} tabIndex={0}>
 {tab==='Overview'?<><div className="panel-header"><h2>Registration details</h2></div><div className="panel-body">{photograph && <img className="registry-photo" src={'/'+kind+'/'+record.public_id+'/documents/'+photograph.public_id+'?preview=1'} alt={meta.singular+' photograph'}/>}<dl className="detail-list">{fields[kind].map(f=>{let value=record[f.key]; if(f.key==='revenue_head_id')value=record.revenue_head?.name; if(f.key==='park_id')value=record.park?.name; if(f.key==='lga_id')value=record.lga?.name; if(f.key==='route_id')value=record.route?optionName(record.route):null; if(f.type==='datetime-local' && value)value=String(value).replace('T',' ').slice(0,19); if(kind==='fee-configurations' && value==null)value=f.key==='effective_to'?'No expiry':f.source || f.key==='vehicle_type'?'All / default':'Not recorded'; return <div key={f.key}><dt>{f.label}</dt><dd>{String(value??'Not recorded')}</dd></div>;})}</dl>{kind==='fee-configurations' && <p className="notice">Historical tickets retain their original amount, currency and fee snapshots. Effective terms cannot be overwritten.</p>}</div></>:
 tab==='Documents' && related.documents?<><DataTable rows={related.documents.data} page={related.documents} rowKey={r=>r.public_id} columns={[{key:'name',label:'Document',render:r=>r.original_name},{key:'category',label:'Category',render:r=>r.category.replaceAll('_',' ')},{key:'type',label:'Type / size',render:r=>r.mime_type+' · '+Math.ceil(r.size_bytes/1024)+' KB'},{key:'action',label:'Action',render:r=><a className="text-link" href={'/'+kind+'/'+record.public_id+'/documents/'+r.public_id}>Download</a>}]}/>{can_update && <DocumentUploader kind={kind} id={record.public_id}/>}</>:
 ['Drivers','Vehicles','Current Assignment','Assignment History'].includes(tab) && related.assignments?<><div className="panel-header"><div><h2>{tab}</h2><p>Assignment history is retained. Current assignments have active status and an open period.</p></div>{can('manage_assignment') && <Link className="button secondary" href="/assignments/create">Create assignment</Link>}</div><AssignmentTable records={tab==='Current Assignment'?(related.current_assignments??related.assignments):related.assignments}/></>:
 tab==='Parks' && related.parks?<DataTable rows={related.parks.data} page={related.parks} rowKey={r=>r.public_id} columns={[{key:'name',label:'Park',render:r=>r.name},{key:'status',label:'Status',render:r=><StatusBadge status={r.status}/>}]}/>:
 tab==='Routes' && related.routes?<DataTable rows={related.routes.data} page={related.routes} rowKey={r=>r.public_id+'-'+r.pivot.park_id} columns={[{key:'name',label:'Route',render:r=>optionName(r)},{key:'status',label:'Approval',render:r=><StatusBadge status={r.pivot.status}/>}]}/>:
 tab==='Configurations' && related.fees?<DataTable rows={related.fees.data} page={related.fees} rowKey={r=>r.public_id} columns={[{key:'amount',label:'Amount (NGN)',render:r=><Link className="text-link" href={'/fee-configurations/'+r.public_id}>{r.amount}</Link>},{key:'start',label:'Effective from (UTC)',render:r=>r.effective_from?.replace('T',' ').slice(0,16)},{key:'status',label:'Status',render:r=><StatusBadge status={r.status}/>}]}/>:
 tab==='Activity'?activities.length?<ul className="activity-list">{activities.map((a,i)=><li key={i}><span className="activity-dot"/><div><strong>{a.description.replaceAll('_',' ')}</strong><p>{a.created_at.replace('T',' ').slice(0,19)} UTC</p></div></li>)}</ul>:<EmptyState title="No accessible activity" description="Audit history requires oversight permission and recorded changes."/>:
 <EmptyState title={'No '+tab.toLowerCase()+' records'} description="This workflow will be available in its approved milestone."/>}
 </section></AppLayout>;
}
