import {router,useForm} from '@inertiajs/react';
import {useState} from 'react';
import AppLayout from '@/Layouts/AppLayout';
import PageHeader from '@/Components/App/PageHeader';
import FormField from '@/Components/Forms/FormField';
import ConfirmDialog from '@/Components/Feedback/ConfirmDialog';
import MoneyDisplay from '@/Components/Finance/MoneyDisplay';
import {EmptyState} from '@/Components/Feedback/States';
type Props={period:{from:string;to:string};entries:{id:number;transaction_reference:string;amount:string;currency:string}[];eligible_count:number;idempotency_key:string};
function SettlementForm({period,entries,eligible_count,idempotency_key}:Props){const form=useForm({...period,scenario:'matched',transaction_ids:[] as number[],idempotency_key});const [confirm,setConfirm]=useState(false);const toggle=(id:number)=>form.setData('transaction_ids',form.data.transaction_ids.includes(id)?form.data.transaction_ids.filter(n=>n!==id):[...form.data.transaction_ids,id]);return <><form onSubmit={e=>{e.preventDefault();setConfirm(true);}}><section className="panel"><div className="panel-body"><FormField id="settlement-scenario" label="Demo scenario" error={form.errors.scenario}><select id="settlement-scenario" value={form.data.scenario} onChange={e=>form.setData('scenario',e.target.value)}><option value="matched">Matched provider batch</option><option value="amount_mismatch">Amount mismatch (first item short by NGN 0.01)</option></select></FormField><p className="muted small">Amounts come from the selected immutable credits. Synthetic fees are zero. No government bank account has been configured.</p><button className="button secondary" type="button" onClick={()=>form.setData('transaction_ids',form.data.transaction_ids.length===entries.length?[]:entries.map(e=>e.id))}>{form.data.transaction_ids.length===entries.length?'Clear selection':'Select displayed entries'}</button><p>{form.data.transaction_ids.length} selected · {eligible_count} eligible {eligible_count>entries.length&&`(showing first ${entries.length}; create additional batches for the rest)`}</p></div>{entries.length?<div className="table-scroll" tabIndex={0} role="region" aria-label="Eligible ledger credits"><table><thead><tr><th scope="col">Select</th><th scope="col">Ledger reference</th><th scope="col">Credit amount</th></tr></thead><tbody>{entries.map(e=><tr key={e.id}><td><input type="checkbox" aria-label={'Select '+e.transaction_reference} checked={form.data.transaction_ids.includes(e.id)} onChange={()=>toggle(e.id)}/></td><td>{e.transaction_reference}</td><td><MoneyDisplay amount={e.amount} currency={e.currency}/></td></tr>)}</tbody></table></div>:<EmptyState title="No eligible credits in this period" description="Only successful, unreversed demo credits that have never been batched can be selected."/>}<div className="panel-body">{Object.entries(form.errors).map(([k,v])=><p key={k} className="field-error" role="alert">{v}</p>)}<button className="button" disabled={form.processing||form.data.transaction_ids.length===0}>{form.processing?'Recording…':'Record demo settlement'}</button></div></section></form><ConfirmDialog open={confirm} title="Record this demo settlement?" description="The selected provider batch and its server-calculated amounts will be retained. No real treasury funds are transferred." onClose={()=>setConfirm(false)} onConfirm={()=>{setConfirm(false);form.post('/finance/settlements');}}/></>;}
export default function Create(props:Props){const [dates,setDates]=useState(props.period);return <AppLayout title="Create demo settlement" breadcrumbs={[{label:'Settlements',href:'/finance/settlements'},{label:'Create demo settlement'}]}><PageHeader title="Create demo settlement" description="Select successful demo credits and record a synthetic provider batch."/><p className="notice demo-payment-banner"><strong>DEMO SETTLEMENT MODE</strong> — Simulated funds only. Dates include both selected days in Africa/Lagos.</p><form className="filter-bar" onSubmit={e=>{e.preventDefault();router.get('/finance/settlements/create',dates);}}>{(['from','to'] as const).map(k=><FormField key={k} id={'settlement-'+k} label={k==='from'?'Period start':'Period end'}><input type="date" id={'settlement-'+k} required value={dates[k]} onChange={e=>setDates({...dates,[k]:e.target.value})}/></FormField>)}<button className="button secondary">Load eligible credits</button></form><SettlementForm key={props.idempotency_key} {...props}/></AppLayout>;}
