import {Link,useForm} from '@inertiajs/react';
import FinanceListControls from '@/Components/Finance/FinanceListControls';
import AppLayout from '@/Layouts/AppLayout';
import PageHeader from '@/Components/App/PageHeader';
import FormField from '@/Components/Forms/FormField';
import StatusBadge from '@/Components/Data/StatusBadge';
import Pagination from '@/Components/Data/Pagination';
import MoneyDisplay from '@/Components/Finance/MoneyDisplay';
import {EmptyState} from '@/Components/Feedback/States';
import {dateTime} from '@/lib/formatters';
import type {Paginated} from '@/types';
import type {Settlement} from '@/types/settlements';
export default function Index({records,filters,can_create}:{records:Paginated<Settlement>;filters:{search?:string;status?:string;from?:string;to?:string;sort?:string;order?:string};can_create:boolean}){const form=useForm({from:filters.from??'',to:filters.to??'',sort:filters.sort??'created_at',order:filters.order??'desc',search:filters.search??'',status:filters.status??''});return <AppLayout title="Settlements" breadcrumbs={[{label:'Settlements'}]}><PageHeader title="Settlements" description="Retained provider batches with direct links to their ledger sources." actions={can_create&&<Link className="button" href="/finance/settlements/create">Create demo settlement</Link>}/><form className="filter-bar" onSubmit={e=>{e.preventDefault();form.get('/finance/settlements');}}><FormField id="settlement-search" label="Settlement reference"><input id="settlement-search" maxLength={190} value={form.data.search} onChange={e=>form.setData('search',e.target.value)}/></FormField><FormField id="settlement-status" label="Status"><select id="settlement-status" value={form.data.status} onChange={e=>form.setData('status',e.target.value)}><option value="">All statuses</option>{['pending','processing','settled','exception','reversed'].map(s=><option key={s} value={s}>{s}</option>)}</select></FormField><FinanceListControls values={form.data} onChange={(key,value)=>form.setData(key,value)} sorts={[['created_at','Batch recorded date'],['settlement_reference','Reference'],['gross_amount','Gross amount'],['net_amount','Net amount'],['settled_at','Settled date']]} dateLabel="Batch recorded" errors={form.errors}/><button className="button" disabled={form.processing}>{form.processing?'Applying…':'Apply filters'}</button><Link className="button secondary" href="/finance/settlements">Reset</Link></form><section className="panel">{records.data.length?<div className="table-scroll" tabIndex={0} role="region" aria-label="Settlement batches"><table><thead><tr>{['Reference','Provider','Gross','Net','Status','Settled at'].map(s=><th scope="col" key={s}>{s}</th>)}</tr></thead><tbody>{records.data.map(s=><tr key={s.public_id}><td><Link className="text-link" href={'/finance/settlements/'+s.public_id}>{s.settlement_reference}</Link></td><td>{s.provider}</td><td><MoneyDisplay amount={s.gross_amount} currency={s.currency}/></td><td><MoneyDisplay amount={s.net_amount} currency={s.currency}/></td><td><StatusBadge status={s.status}/></td><td>{s.settled_at?dateTime(s.settled_at):'Pending'}</td></tr>)}</tbody></table></div>:<EmptyState title="No settlement batches" description="Finance staff can create a synthetic provider batch from eligible demo credits."/>}<Pagination page={records}/></section></AppLayout>;}
