import {Link} from '@inertiajs/react';
import AppLayout from '@/Layouts/AppLayout';
import PageHeader from '@/Components/App/PageHeader';
import StatusBadge from '@/Components/Data/StatusBadge';
import Pagination from '@/Components/Data/Pagination';
import MoneyDisplay from '@/Components/Finance/MoneyDisplay';
import {dateTime} from '@/lib/formatters';
import type {Paginated} from '@/types';
import type {Settlement} from '@/types/settlements';
export default function Show({settlement:s,demo,items}:{settlement:Settlement;demo:boolean;items:Paginated<{id:number;amount:string;status:string;transaction_reference:string;ledger_url:string|null}>}){return <AppLayout title={s.settlement_reference} breadcrumbs={[{label:'Settlements',href:'/finance/settlements'},{label:s.settlement_reference}]}><PageHeader title={s.settlement_reference} description="Retained provider settlement and its ledger sources." actions={<StatusBadge status={s.status}/>}/>{demo&&<p className="notice demo-payment-banner"><strong>DEMO SETTLEMENT</strong> — No real treasury transfer occurred.</p>}<section className="panel"><div className="panel-body"><dl className="detail-list">{[['Gross',s.gross_amount],['Provider fees',s.provider_fees],['Net',s.net_amount]].map(([k,v])=><div key={k}><dt>{k}</dt><dd><MoneyDisplay amount={v} currency={s.currency}/></dd></div>)}{[['Provider',s.provider],['Provider reference',s.provider_settlement_reference],['Period start',dateTime(s.period_start)],['Period end (exclusive)',dateTime(s.period_end)],['Settled at',s.settled_at?dateTime(s.settled_at):'Pending'],['Government account reference',s.government_account_reference??'Not configured']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v??'Not recorded'}</dd></div>)}</dl></div><div className="table-scroll" tabIndex={0} role="region" aria-label="Settlement items"><table><thead><tr><th scope="col">Ledger reference</th><th scope="col">Provider recorded amount</th><th scope="col">Status</th></tr></thead><tbody>{items.data.map(i=><tr key={i.id}><td>{i.ledger_url?<Link className="text-link" href={i.ledger_url}>{i.transaction_reference}</Link>:i.transaction_reference}</td><td><MoneyDisplay amount={i.amount} currency={s.currency}/></td><td><StatusBadge status={i.status}/></td></tr>)}</tbody></table></div><Pagination page={items}/></section></AppLayout>;}
