import {useForm} from '@inertiajs/react';
import {useState} from 'react';
import FormField from '@/Components/Forms/FormField';
import ConfirmDialog from '@/Components/Feedback/ConfirmDialog';
import useFieldOnline from '@/hooks/useFieldOnline';
import type {OperationalRecord,RecordKind} from '@/types/incidents';
export default function EvidencePanel({record,kind,idempotency_key}:{record:OperationalRecord;kind:RecordKind;idempotency_key:string}){
 const online=useFieldOnline(),[confirm,setConfirm]=useState(false),f=useForm({file:null as File|null,idempotency_key});
 return <section className="panel"><div className="panel-header"><h2>Private evidence</h2></div><div className="panel-body">{record.evidence.length?<ul className="incident-evidence">{record.evidence.map(m=><li key={m.public_id}><a className="text-link" href={m.href}>{m.name||'Evidence file'}</a><span className="muted small"> {m.mime_type} · {Math.ceil(m.size_bytes/1024)} KB</span></li>)}</ul>:<p className="muted">No evidence uploaded.</p>}{record.can_upload&&<form className="payment-form" onSubmit={e=>{e.preventDefault();if(online&&f.data.file&&!f.processing)setConfirm(true);}}><FormField id="evidence-file" label="Add evidence" error={f.errors.file} hint="JPEG, PNG or PDF up to 5 MB. Retained evidence cannot be replaced or deleted here."><input id="evidence-file" type="file" accept="image/jpeg,image/png,application/pdf" required onChange={e=>f.setData('file',e.target.files?.[0]??null)}/></FormField>{f.errors.idempotency_key&&<p role="alert">{f.errors.idempotency_key}</p>}{f.progress&&<progress value={f.progress.percentage} max={100} aria-label="Evidence upload progress"/>}<button className="button" disabled={!online||!f.data.file||f.processing}>{f.processing?'Uploading…':'Review and upload evidence'}</button></form>}</div><ConfirmDialog open={confirm} title="Retain private evidence" description="Attach this file to the record with your identity and a retained audit entry?" onClose={()=>setConfirm(false)} onConfirm={()=>{setConfirm(false);f.post('/'+kind+'/'+record.public_id+'/evidence',{forceFormData:true,preserveScroll:true});}}/></section>;
}
