import {Link,useForm} from '@inertiajs/react';
import AppLayout from '@/Layouts/AppLayout';
import PageHeader from '@/Components/App/PageHeader';
import FormField from '@/Components/Forms/FormField';
import StatusBadge from '@/Components/Data/StatusBadge';
import Pagination from '@/Components/Data/Pagination';
import {EmptyState} from '@/Components/Feedback/States';
import {dateTime} from '@/lib/formatters';
import type {RecordKind,RecordListProps} from '@/types/incidents';
export default function RecordList({kind,records,filters,parks,statuses,can_create=false}:RecordListProps&{kind:RecordKind}){
 const title=kind[0].toUpperCase()+kind.slice(1),base='/'+kind;
 const f=useForm({search:filters.search??'',status:filters.status??'',category:filters.category??'',park:filters.park??'',from:filters.from??'',to:filters.to??'',order:filters.order??'desc'});
 return <AppLayout title={title}><PageHeader title={title} description="Scoped observations, private evidence and retained review history." actions={can_create&&<Link className="button" href="/incidents/create">Report incident</Link>}/><form className="filter-bar" onSubmit={e=>{e.preventDefault();f.get(base);}}><FormField id="record-search" label="Reference" error={f.errors.search}><input id="record-search" maxLength={100} value={f.data.search} onChange={e=>f.setData('search',e.target.value)}/></FormField><FormField id="record-status" label="Status" error={f.errors.status}><select id="record-status" value={f.data.status} onChange={e=>f.setData('status',e.target.value)}><option value="">All statuses</option>{statuses.map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></FormField><FormField id="record-category" label={kind==='inspections'?'Inspection type':'Category'} error={f.errors.category}><input id="record-category" maxLength={80} value={f.data.category} onChange={e=>f.setData('category',e.target.value)}/></FormField><FormField id="record-park" label="Park" error={f.errors.park}><select id="record-park" value={f.data.park} onChange={e=>f.setData('park',e.target.value)}><option value="">All scoped parks</option>{parks.map(p=><option key={p.public_id} value={p.public_id}>{p.name}</option>)}</select></FormField>{(['from','to'] as const).map(k=><FormField key={k} id={'record-'+k} label={k==='from'?'Occurred from (Lagos)':'Occurred through (Lagos)'} error={f.errors[k]}><input id={'record-'+k} type="date" value={f.data[k]} onChange={e=>f.setData(k,e.target.value)}/></FormField>)}<FormField id="record-order" label="Date order" error={f.errors.order}><select id="record-order" value={f.data.order} onChange={e=>f.setData('order',e.target.value)}><option value="desc">Newest first</option><option value="asc">Oldest first</option></select></FormField><button className="button" disabled={f.processing}>Apply filters</button><Link className="button secondary" href={base}>Reset</Link></form><section className="panel">{records.data.length?<div className="table-scroll" tabIndex={0} role="region" aria-label={title}><table><thead><tr>{['Reference','Category / type','Park','Status','Occurred at'].map(t=><th key={t} scope="col">{t}</th>)}</tr></thead><tbody>{records.data.map(r=><tr key={r.public_id}><td><Link className="text-link" href={base+'/'+r.public_id}>{r.reference}</Link></td><td>{r.category.replaceAll('_',' ')}</td><td>{r.park?.name??'Unavailable'}</td><td><StatusBadge status={r.status}/></td><td>{dateTime(r.occurred_at)}</td></tr>)}</tbody></table></div>:<EmptyState title={'No '+kind} description="No records match your current scope and filters."/>}<Pagination page={records}/></section></AppLayout>;
}
