import {Link} from '@inertiajs/react';
import type {ReactNode} from 'react';
import OperationalLayout from '@/Components/Incidents/OperationalLayout';
import PageHeader from '@/Components/App/PageHeader';
import StatusBadge from '@/Components/Data/StatusBadge';
import Pagination from '@/Components/Data/Pagination';
import EvidencePanel from '@/Components/Incidents/EvidencePanel';
import {dateTime} from '@/lib/formatters';
import type {OperationalRecord,RecordKind} from '@/types/incidents';
export default function RecordDetail({record,kind,idempotency_key,actions,children,field=false}:{record:OperationalRecord;kind:RecordKind;idempotency_key:string;actions?:ReactNode;children?:ReactNode;field?:boolean}){

 return <OperationalLayout field={field} title={record.reference}>{field?<><p className="field-lead">{record.category.replaceAll('_',' ')}</p>{actions}</>:<PageHeader title={record.reference} description={record.category.replaceAll('_',' ')} actions={actions}/>}<div className="incident-detail"><section className="panel"><div className="panel-body"><StatusBadge status={record.status}/><dl className="incident-facts"><div><dt>Occurred at</dt><dd>{dateTime(record.occurred_at)}</dd></div>{(['park','operator','driver','vehicle'] as const).map(k=><div key={k}><dt>{k[0].toUpperCase()+k.slice(1)}</dt><dd>{record[k]?.name??'Not recorded'}</dd></div>)}</dl><h2>Recorded observation</h2><p className="incident-text">{record.description??'No notes recorded.'}</p><p className="muted small">This observation does not establish guilt, impose a penalty or change financial records.</p>{record.resolution&&<><h2>Resolution</h2><p className="incident-text">{record.resolution}</p><p className="muted small">Resolved {dateTime(record.resolved_at??'')}</p></>}{record.inspection&&<Link className="text-link" href={'/inspections/'+record.inspection.public_id}>Inspection {record.inspection.reference}</Link>}{record.violations&&<><h2>Related violations</h2>{record.violations.length?<ul>{record.violations.map(v=><li key={v.public_id}><Link className="text-link" href={'/violations/'+v.public_id}>{v.reference}</Link> · {v.status}</li>)}</ul>:<p>No violations recorded.</p>}</>}{children}</div></section><EvidencePanel key={'evidence-'+idempotency_key} record={record} kind={kind} idempotency_key={idempotency_key}/><section className="panel"><div className="panel-header"><h2>Retained history</h2></div><div className="panel-body"><ol className="incident-history">{record.history.data.map((h,i)=><li key={i}><strong>{h.event.replaceAll('_',' ')}</strong><p className="muted small">{h.actor} · {dateTime(h.at)}</p>{h.to&&<p>{h.from? h.from.replaceAll('_',' ')+' → ':''}{h.to.replaceAll('_',' ')}</p>}{h.reason&&<p className="incident-text">{h.reason}</p>}</li>)}</ol><Pagination page={record.history}/></div></section></div><Link className="text-link" href={field?'/field/':'/'+kind}>{field?'Return to field home':'Back to '+kind}</Link></OperationalLayout>;
}
