import { useForm, usePage } from '@inertiajs/react';
import AppLayout from '@/Layouts/AppLayout';
import PageHeader from '@/Components/App/PageHeader';
import FormField from '@/Components/Forms/FormField';
import DataTable from '@/Components/Data/DataTable';
import { dateTime } from '@/lib/formatters';
import type { SharedProps } from '@/types';
type Session = { ip_address: string; user_agent: string; last_active_at: string; is_current: boolean };
export default function Security({ sessions }: { sessions: Session[] }) {
    const { auth } = usePage<SharedProps>().props;
    const form = useForm({ current_password: '', password: '', password_confirmation: '' });
    const revoke = useForm({ current_password: '' });
    return <AppLayout title="Account Security" breadcrumbs={[{ label: 'Account' }, { label: 'Security' }]}><PageHeader title="Account security" description="Keep your password and active sessions secure." />{auth.user?.must_change_password && <div className="notice info">You must change your password before accessing other pages.</div>}
        <form className="panel form-panel" style={{ marginBottom: 24 }} onSubmit={e => { e.preventDefault(); form.put('/account/security/password', { onSuccess: () => form.reset() }); }}><div className="panel-header"><div><h2>Change password</h2><p>At least 12 characters, mixed case and a number.</p></div></div><div className="panel-body"><div className="form-grid">{(['current_password', 'password', 'password_confirmation'] as const).map(key => <FormField key={key} id={key} label={{ current_password: 'Current password', password: 'New password', password_confirmation: 'Confirm new password' }[key]} error={form.errors[key]}><input id={key} type="password" autoComplete={key === 'current_password' ? 'current-password' : 'new-password'} required value={form.data[key]} onChange={e => form.setData(key, e.target.value)} aria-invalid={!!form.errors[key]} aria-describedby={form.errors[key] ? `${key}-error` : undefined} /></FormField>)}</div><div className="form-actions"><button className="button" disabled={form.processing}>Change password</button></div></div></form>
        <section className="panel form-panel"><div className="panel-header"><div><h2>Active sessions</h2><p>Sessions currently associated with your account</p></div></div><DataTable rows={sessions} rowKey={session => `${session.ip_address}-${session.last_active_at}-${session.is_current}`} emptyTitle="No stored sessions" columns={[{ key: 'device', label: 'Device', render: session => <span className="small">{session.user_agent?.slice(0, 90) || 'Unknown device'}{session.is_current && <span className="pill">This session</span>}</span> }, { key: 'address', label: 'IP address', render: session => session.ip_address }, { key: 'time', label: 'Last active', render: session => dateTime(session.last_active_at) }]} />
        {!auth.user?.must_change_password && <form className="panel-body" onSubmit={e => { e.preventDefault(); revoke.delete('/account/security/sessions', { onSuccess: () => revoke.reset() }); }}><FormField label="Confirm current password" id="revoke-password" error={revoke.errors.current_password}><input id="revoke-password" type="password" required autoComplete="current-password" value={revoke.data.current_password} onChange={e => revoke.setData('current_password', e.target.value)} aria-invalid={!!revoke.errors.current_password} /></FormField><div className="form-actions"><button className="button secondary" disabled={revoke.processing}>Sign out other sessions</button></div></form>}</section></AppLayout>;
}
