import {Link,useForm} from '@inertiajs/react';
import {useState} from 'react';
import AppLayout from '@/Layouts/AppLayout';
import PageHeader from '@/Components/App/PageHeader';
import ConfirmDialog from '@/Components/Feedback/ConfirmDialog';
import FormField from '@/Components/Forms/FormField';
import MoneyDisplay from '@/Components/Finance/MoneyDisplay';
type Ticket={public_id:string;ticket_reference:string;amount:string;currency:string;vehicle:string|null;park:string|null;status:string;payment_status:string};
export default function DemoPay({ticket,idempotency_key}:{ticket:Ticket;idempotency_key:string}) {
 const form=useForm({scenario:'successful',idempotency_key});const [confirm,setConfirm]=useState(false);const eligible=ticket.status==='pending'&&['unpaid','failed'].includes(ticket.payment_status);
 return <AppLayout title="Demo payment" breadcrumbs={[{label:'Tickets',href:'/tickets'},{label:ticket.ticket_reference,href:'/tickets/'+ticket.public_id},{label:'Demo payment'}]}><PageHeader title="Demo payment" description="Simulate an outcome for this ticket using the controlled demo gateway."/><p className="notice demo-payment-banner"><strong>DEMO PAYMENT MODE</strong><br/>No real funds will be charged.</p><section className="panel"><div className="panel-body"><h2 className="ticket-reference">{ticket.ticket_reference}</h2><div className="ticket-total"><strong><MoneyDisplay amount={ticket.amount} currency={ticket.currency}/></strong></div><dl className="detail-list"><div><dt>Vehicle</dt><dd>{ticket.vehicle??'Not recorded'}</dd></div><div><dt>Park</dt><dd>{ticket.park??'Not recorded'}</dd></div></dl>{!eligible&&<p className="notice">This ticket is not eligible for another payment attempt. View its payment history for pending or completed attempts.</p>}<form className="payment-form" onSubmit={e=>{e.preventDefault();setConfirm(true);}}><FormField id="scenario" label="Demo outcome" error={form.errors.scenario}><select id="scenario" value={form.data.scenario} onChange={e=>form.setData('scenario',e.target.value)} disabled={!eligible}><option value="successful">Simulate successful payment</option><option value="failed">Simulate failed payment</option><option value="pending">Simulate pending payment</option></select></FormField>{form.errors.idempotency_key&&<p className="field-error" role="alert">{form.errors.idempotency_key}</p>}<div className="form-actions"><Link className="button secondary" href={'/tickets/'+ticket.public_id}>Back to ticket</Link><button className="button" disabled={form.processing||!eligible}>Confirm demo outcome</button></div></form></div></section><ConfirmDialog open={confirm} title="Record this demo payment?" description="The server will record the selected outcome. Only verified success creates a ledger credit and receipt. No real funds move." onClose={()=>setConfirm(false)} onConfirm={()=>{setConfirm(false);form.post('/tickets/'+ticket.public_id+'/pay');}}/></AppLayout>;
}
