import {Link,useForm} from '@inertiajs/react';
import {useState} from 'react';
import AppLayout from '@/Layouts/AppLayout';
import PageHeader from '@/Components/App/PageHeader';
import StatusBadge from '@/Components/Data/StatusBadge';
import FormField from '@/Components/Forms/FormField';
import ConfirmDialog from '@/Components/Feedback/ConfirmDialog';
import MoneyDisplay from '@/Components/Finance/MoneyDisplay';
import {dateTime} from '@/lib/formatters';
import type {FinancialRow} from '@/types/payments';
type Props={can_request_refund:boolean;refunds:import('@/types/corrections').Correction[];payment:FinancialRow&{provider_reference:string;failed_at:string|null;reversed_at:string|null;demo:boolean};ticket:{public_id:string;ticket_reference:string;vehicle:string|null;park:string|null;status:string};receipt:{public_id:string;receipt_number:string}|null;ledger:FinancialRow[];can_resolve:boolean;can_reverse:boolean;idempotency_key:string};
function PaymentActions({payment,can_resolve,can_reverse,idempotency_key}:Props){
 const resolve=useForm({scenario:'successful',idempotency_key});const reverse=useForm({reason:'',idempotency_key});const [confirmation,setConfirmation]=useState<'resolve'|'reverse'|null>(null);
 return <>{can_resolve&&<section className="panel ticket-review"><div className="panel-body"><h2>Resolve pending demo attempt</h2><p className="muted small">The same attempt is retained. Choose the final simulated outcome.</p><form className="payment-form" onSubmit={e=>{e.preventDefault();setConfirmation('resolve');}}><FormField id="resolve-scenario" label="Final demo outcome" error={resolve.errors.scenario}><select id="resolve-scenario" value={resolve.data.scenario} onChange={e=>resolve.setData('scenario',e.target.value)}><option value="successful">Successful</option><option value="failed">Failed</option></select></FormField>{resolve.errors.idempotency_key&&<p className="field-error" role="alert">{resolve.errors.idempotency_key}</p>}<button className="button" disabled={resolve.processing}>Resolve demo payment</button></form></div></section>}{can_reverse&&<section className="panel ticket-review"><div className="panel-body"><h2>Controlled demo reversal</h2><p className="muted small">A reversal adds a matching debit, retains the original credit and invalidates the receipt. No real refund is sent.</p><form className="payment-form" onSubmit={e=>{e.preventDefault();setConfirmation('reverse');}}><FormField id="reversal-reason" label="Reversal reason" error={reverse.errors.reason}><textarea id="reversal-reason" required maxLength={2000} value={reverse.data.reason} onChange={e=>reverse.setData('reason',e.target.value)}/></FormField>{reverse.errors.idempotency_key&&<p className="field-error" role="alert">{reverse.errors.idempotency_key}</p>}<button className="button danger" disabled={reverse.processing}>Reverse demo payment</button></form></div></section>}<ConfirmDialog open={confirmation!==null} title={confirmation==='reverse'?'Reverse this demo payment?':'Resolve this pending payment?'} description={confirmation==='reverse'?'The original credit remains and a new debit records the reversal. The receipt will no longer verify as valid.':'Record the final outcome on this pending demo attempt. Only success creates a receipt and credit.'} onClose={()=>setConfirmation(null)} onConfirm={()=>{const action=confirmation;setConfirmation(null);if(action==='reverse')reverse.post('/payments/'+payment.public_id+'/reverse');else resolve.post('/payments/'+payment.public_id+'/simulate');}}/></>;
}
export default function Show(props:Props){const {payment:p,ticket,receipt,ledger}=props;
 return <AppLayout title={p.payment_reference??'Payment'} breadcrumbs={[{label:'Payments',href:'/payments'},{label:p.payment_reference??'Payment'}]}><PageHeader title={p.payment_reference??'Payment'} description="Payment attempt and its retained financial records." actions={receipt&&<Link className="button" href={'/receipts/'+receipt.public_id}>View receipt</Link>}/>{p.demo&&<p className="notice demo-payment-banner"><strong>DEMO PAYMENT MODE</strong> — No real funds were charged.</p>}<section className="panel"><div className="panel-body"><div className="ticket-total"><strong><MoneyDisplay amount={p.amount} currency={p.currency}/></strong><StatusBadge status={p.status??''}/></div><dl className="detail-list"><div><dt>Ticket</dt><dd><Link className="text-link" href={'/tickets/'+ticket.public_id}>{ticket.ticket_reference}</Link></dd></div>{[['Vehicle',ticket.vehicle],['Park',ticket.park],['Provider',p.provider],['Provider reference',p.provider_reference],['Channel',p.channel],['Initiated at',dateTime(p.initiated_at)],['Paid at',p.paid_at?dateTime(p.paid_at):'Not paid'],['Failed at',p.failed_at?dateTime(p.failed_at):'—'],['Reversed at',p.reversed_at?dateTime(p.reversed_at):'—']].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value??'Not recorded'}</dd></div>)}</dl>{!receipt&&<p className="notice">No valid receipt exists for a failed or pending payment.</p>}{ledger.length>0&&<div className="related-finance"><h2>Ledger records</h2>{ledger.map(t=><p key={t.public_id}><Link className="text-link" href={'/finance/ledger/'+t.public_id}>{t.transaction_reference}</Link> · {t.direction} · <MoneyDisplay amount={t.amount} currency={t.currency}/></p>)}</div>}</div></section>{props.can_request_refund&&<p><Link className="button" href={'/payments/'+p.public_id+'/refund'}>Request refund</Link></p>}{props.refunds.length>0&&<section className="panel"><div className="panel-body"><h2>Refund history</h2>{props.refunds.map(r=><p key={r.public_id}><Link className="text-link" href={'/finance/refunds/'+r.public_id}>{r.reference}</Link> · <MoneyDisplay amount={r.amount} currency={r.currency}/> · <StatusBadge status={r.status}/></p>)}</div></section>}<PaymentActions key={props.idempotency_key} {...props}/></AppLayout>;
}
