import PublicLayout from '@/Layouts/PublicLayout';
import StatusBadge from '@/Components/Data/StatusBadge';
import MoneyDisplay from '@/Components/Finance/MoneyDisplay';
import {dateTime} from '@/lib/formatters';
type Verification={ticket_reference:string;vehicle:string|null;park:string|null;fee_name:string;amount:string;currency:string;issued_at:string;expires_at:string|null;ticket_status:string;payment_status:string;valid:boolean;result:string};
export default function TicketVerification({verification:v}:{verification:Verification|null}) {
    const awaiting=v?.ticket_status==='pending'&&['unpaid','pending','failed'].includes(v.payment_status);
    return <PublicLayout title="Ticket verification"><article className="panel verification-card"><div className={'verification-banner '+(v?.valid?'valid':awaiting?'pending':'invalid')}><p className="eyebrow">PUBLIC TICKET VERIFICATION</p><h1>{v?.result??'Invalid or not found'}</h1><p>{v?(v.valid?'This ticket is paid and within its recorded validity period.':awaiting?'This ticket exists, but it does not confirm a completed payment.':'This ticket must not be accepted as valid for use.'):'The verification code does not identify a ticket. Check the QR code or contact the issuing park.'}</p></div>{v&&<div className="panel-body"><dl className="detail-list">{[['Ticket reference',v.ticket_reference],['Vehicle',v.vehicle??'Not recorded'],['Park',v.park??'Not recorded'],['Revenue type',v.fee_name],['Issued at',dateTime(v.issued_at)],['Expires at',v.expires_at?dateTime(v.expires_at):'No expiry configured']].map(([label,value])=><div key={label}><dt>{label}</dt><dd className={label==='Ticket reference'?'ticket-reference':''}>{value}</dd></div>)}<div><dt>Amount</dt><dd><MoneyDisplay amount={v.amount} currency={v.currency}/></dd></div><div><dt>Ticket status</dt><dd><StatusBadge status={v.ticket_status}/></dd></div><div><dt>Payment status</dt><dd><StatusBadge status={v.payment_status}/></dd></div></dl><p className="notice">Verification shows the latest recorded status. An unpaid ticket is not a payment receipt.</p></div>}</article></PublicLayout>;
}
