import { Link } from '@inertiajs/react';
import { Bar, BarChart, CartesianGrid, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Wallet, ArrowDownLeft, ArrowUpRight, ReceiptText } from 'lucide-react';
import StatCard from '@/Components/Data/StatCard';
import MoneyDisplay from '@/Components/Finance/MoneyDisplay';
import StatusBadge from '@/Components/Data/StatusBadge';
import { EmptyState } from '@/Components/Feedback/States';
import { dateTime, money } from '@/lib/formatters';
import type { CountGroup, FinanceData, RevenueGroup } from '@/types/dashboards';

const axisAmount = new Intl.NumberFormat('en-NG', { notation: 'compact', maximumFractionDigits: 1 });
const tick = { fill: '#52677b', fontSize: 11 };
function AmountTable({ rows, currency }: { rows: RevenueGroup[]; currency: string }) {
    return <details className="chart-data"><summary>View exact figures and records</summary><div className="table-scroll" tabIndex={0} role="region" aria-label="Financial figures"><table><thead><tr><th scope="col">Group</th><th scope="col">Credits</th><th scope="col">Debits</th><th scope="col">Net revenue</th><th scope="col">Entries</th></tr></thead><tbody>{rows.map(row => <tr key={row.date ?? row.id ?? row.name}><th scope="row">{row.href ? <Link href={row.href}>{row.name}</Link> : row.name}</th><td><MoneyDisplay amount={row.gross} currency={currency} /></td><td><MoneyDisplay amount={row.debits} currency={currency} /></td><td><MoneyDisplay amount={row.net} currency={currency} /></td><td>{row.transactions}</td></tr>)}</tbody></table></div></details>;
}
function RevenueBars({ title, rows, currency }: { title: string; rows: RevenueGroup[]; currency: string }) {
    // Numeric conversion is for chart coordinates only. Exact money stays in server-provided strings.
    const chart = rows.slice(0, 10).map(row => ({ ...row, plotted: Number(row.net) }));
    return <section className="panel revenue-panel"><div className="panel-header"><div><h2>{title}</h2><p>Net ledger revenue • {rows.length > 10 ? 'chart shows 10 groups; all figures below' : 'selected period'}</p></div></div>{rows.length ? <><div className="revenue-chart" role="group" aria-label={`${title} chart; exact figures follow`}><ResponsiveContainer width="100%" height="100%"><BarChart accessibilityLayer data={chart} margin={{ top: 12, right: 18, left: 8, bottom: 16 }}><CartesianGrid vertical={false} stroke="#e2e8f0" /><XAxis dataKey="name" tick={tick} tickFormatter={value => String(value).length > 15 ? String(value).slice(0, 14) + '…' : String(value)} /><YAxis tick={tick} width={62} tickFormatter={value => axisAmount.format(Number(value))} /><Tooltip content={({ active, payload }) => active && payload?.length ? <div className="revenue-tooltip"><strong>{payload[0].payload.name}</strong><p>{money(payload[0].payload.net, currency)}</p></div> : null} /><ReferenceLine y={0} stroke="#52677b" /><Bar dataKey="plotted" name="Net revenue" fill="#235e91" isAnimationActive={false} maxBarSize={52} /></BarChart></ResponsiveContainer></div><AmountTable rows={rows} currency={currency} /></> : <EmptyState title="No ledger entries in this period" description="Adjust the dates or filters to find recorded collections." />}</section>;
}
function CountBars({ title, rows }: { title: string; rows: CountGroup[] }) {
    const hasData = rows.some(row => row.count > 0);
    return <section className="panel revenue-panel"><div className="panel-header"><div><h2>{title}</h2><p>Attempts initiated in selected period • current status</p></div></div>{hasData ? <><div className="revenue-chart" role="group" aria-label={`${title} chart; exact counts follow`}><ResponsiveContainer width="100%" height="100%"><BarChart accessibilityLayer data={rows} margin={{ top: 12, right: 18, left: 0, bottom: 16 }}><CartesianGrid vertical={false} stroke="#e2e8f0" /><XAxis dataKey="name" tick={tick} tickFormatter={value => String(value).replaceAll('_', ' ')} /><YAxis tick={tick} allowDecimals={false} width={38} /><Tooltip /><Bar dataKey="count" name="Attempts" fill="#176346" isAnimationActive={false} maxBarSize={48} /></BarChart></ResponsiveContainer></div><ul className="dashboard-count-list">{rows.map(row => <li key={row.name}><span>{row.href ? <Link href={row.href}>{row.name.replaceAll('_', ' ')}</Link> : row.name.replaceAll('_', ' ')}</span><strong>{row.count.toLocaleString('en-NG')}</strong></li>)}</ul></> : <EmptyState title="No payment attempts in this period" description="Failed and pending attempts never contribute ledger revenue." />}</section>;
}
export default function RevenueInsights({ finance }: { finance: FinanceData | null }) {
    if (!finance) return <section className="panel"><EmptyState title="Revenue access restricted" description="Your account can view operational counts only." /></section>;
    const { summary, currency } = finance;
    const trend = finance.revenue_trend.map(row => ({ ...row, plotted: Number(row.net) }));
    return <>
        <div className="section-heading"><h2>Collections in selected period</h2><span>{finance.timezone} • {currency}</span></div>
        <div className="stat-grid revenue-totals">
            <StatCard label="Gross credits" value={<MoneyDisplay amount={summary.gross} currency={currency} />} note="Original credits retained after reversal" icon={ArrowDownLeft} />
            <StatCard label="Debits" value={<MoneyDisplay amount={summary.debits} currency={currency} />} note="Includes controlled demo reversals" icon={ArrowUpRight} />
            <StatCard label="Net revenue" value={<MoneyDisplay amount={summary.net} currency={currency} />} note="Ledger credits minus debits" icon={Wallet} />
            <StatCard label="Ledger transactions" value={summary.transactions.toLocaleString('en-NG')} note="Count of credits and debits" icon={ReceiptText} />
        </div>
        <div className="dashboard-record-links">{finance.ledger_url && <Link className="text-link" href={finance.ledger_url}>View matching ledger records →</Link>}{finance.payments_url && <Link className="text-link" href={finance.payments_url}>View matching payment attempts →</Link>}</div>
        <div className="dashboard-grid"><section className="panel revenue-panel"><div className="panel-header"><div><h2>Revenue trend</h2><p>Daily net ledger revenue, including debit-only days</p></div></div>{trend.length ? <><div className="revenue-chart" role="group" aria-label="Daily net revenue chart; exact figures follow"><ResponsiveContainer width="100%" height="100%"><LineChart accessibilityLayer data={trend} margin={{ top: 12, right: 18, left: 8, bottom: 16 }}><CartesianGrid vertical={false} stroke="#e2e8f0" /><XAxis dataKey="date" tick={tick} minTickGap={24} tickFormatter={value => String(value).slice(5)} /><YAxis tick={tick} width={62} tickFormatter={value => axisAmount.format(Number(value))} /><Tooltip content={({ active, payload }) => active && payload?.length ? <div className="revenue-tooltip"><strong>{payload[0].payload.date}</strong><p>{money(payload[0].payload.net, currency)}</p></div> : null} /><ReferenceLine y={0} stroke="#52677b" /><Line type="linear" dataKey="plotted" name="Net revenue" stroke="#235e91" strokeWidth={2} dot={trend.length < 32} isAnimationActive={false} /></LineChart></ResponsiveContainer></div><AmountTable rows={trend.map(row => ({ ...row, name: row.date }))} currency={currency} /></> : <EmptyState title="No ledger entries in this period" description="Payments and reversals will appear on their ledger occurrence dates." />}</section><CountBars title="Payment status" rows={finance.payment_status} /></div>
        <div className="dashboard-grid"><RevenueBars title="Revenue by LGA" rows={finance.revenue_by_lga} currency={currency} /><RevenueBars title="Revenue by park" rows={finance.revenue_by_park} currency={currency} /></div>
        <div className="dashboard-grid"><RevenueBars title="Revenue by revenue head" rows={finance.revenue_by_revenue_head} currency={currency} /><CountBars title="Payment channel distribution" rows={finance.payment_channels} /></div>
        <section className="panel revenue-panel"><div className="panel-header"><div><h2>Recent transactions</h2><p>Latest six ledger entries in this period</p></div></div>{finance.recent_transactions.length ? <div className="table-scroll" tabIndex={0} role="region" aria-label="Financial figures"><table><thead><tr><th scope="col">Reference</th><th scope="col">Direction</th><th scope="col">Type</th><th scope="col">Amount</th><th scope="col">Occurred at</th></tr></thead><tbody>{finance.recent_transactions.map(row => <tr key={row.reference}><td>{row.href ? <Link className="text-link" href={row.href}>{row.reference}</Link> : row.reference}</td><td><StatusBadge status={row.direction} /></td><td>{row.type}</td><td><MoneyDisplay amount={row.amount} currency={row.currency} /></td><td>{dateTime(row.occurred_at, finance.timezone)}</td></tr>)}</tbody></table></div> : <EmptyState title="No transactions in this period" description="Only committed ledger records appear here." />}</section>
        <p className="notice">Reconciliation status and exceptions will be available in Milestone 10. These totals do not imply treasury settlement.</p>
    </>;
}
