import {Link} from '@inertiajs/react';
import AppLayout from '@/Layouts/AppLayout';
import PageHeader from '@/Components/App/PageHeader';
import ManageForm from '@/Components/Complaints/ManageForm';
import EvidencePanel from '@/Components/Incidents/EvidencePanel';
import {dateTime} from '@/lib/formatters';
import type {Complaint,Choice} from '@/types/complaints';
export default function Show({record:c,can_manage,assignees,transitions,idempotency_key}:{record:Complaint;can_manage:boolean;assignees:Choice[];transitions:string[];idempotency_key:string}){
 return <AppLayout title="Complaint details" retainFormOnError><PageHeader title={c.reference} description="Retained complaint, notes and resolution history." actions={<Link className="button secondary" href="/complaints">Back to complaints</Link>}/><div className="detail-grid"><section className="panel"><div className="panel-header"><h2>Complaint</h2></div><div className="panel-body"><dl className="detail-list"><dt>Status</dt><dd>{c.status.replaceAll('_',' ')}</dd><dt>Category</dt><dd>{c.category}</dd><dt>Source</dt><dd>{c.source.replaceAll('_',' ')}</dd><dt>Park</dt><dd>{c.park?.name??'Unlocated'}</dd><dt>Assigned officer</dt><dd>{c.assignee?.name??'Unassigned'}</dd><dt>Submitted</dt><dd>{dateTime(c.created_at)}</dd>{c.operator&&<><dt>Operator</dt><dd>{c.operator.name}</dd></>}{c.driver&&<><dt>Driver</dt><dd>{c.driver.first_name} {c.driver.last_name}</dd></>}{c.vehicle&&<><dt>Vehicle</dt><dd>{c.vehicle.registration_number}</dd></>}</dl><h3>Description</h3><p className="retained-text">{c.description}</p>{c.contact&&<><h3>Complainant contact</h3><p>{c.contact.complainant_name}</p><p>{c.contact.complainant_phone??'No phone supplied'} · {c.contact.complainant_email??'No email supplied'}</p></>}{c.resolution&&<><h3>Resolution</h3><p className="retained-text">{c.resolution}</p><p className="muted small">Resolved {dateTime(c.resolved_at)}</p></>}</div></section>{can_manage&&c.status!=='closed'?<ManageForm key={idempotency_key} record={c} assignees={assignees} transitions={transitions} idempotency_key={idempotency_key}/>:<section className="panel"><div className="panel-body"><h2>Review access</h2><p>{c.status==='closed'?'This complaint is closed. Its history is retained.':'Help Desk officers manage assignment and resolution. Your access is read only.'}</p></div></section>}</div><section className="panel"><div className="panel-header"><h2>Notes</h2></div><div className="panel-body">{c.notes.length?c.notes.map((n,i)=><article className="complaint-note" key={i}><p className="retained-text">{n.note}</p><p className="muted small">{n.author} · {dateTime(n.created_at)} · {n.is_internal?'Internal':'Shared'}</p></article>):<p>No notes available.</p>}</div></section>{(c.evidence.length>0||c.can_upload)&&<EvidencePanel key={'evidence-'+idempotency_key} record={c} kind="complaints" idempotency_key={idempotency_key}/>}<section className="panel"><div className="panel-header"><h2>Review history</h2></div><div className="panel-body">{c.history.length?<ol>{c.history.map((a,i)=><li key={i}><strong>{a.event.replaceAll('_',' ')}</strong><p>{a.actor} · {dateTime(a.at)}{a.from&&` · ${a.from.replaceAll('_',' ')} → ${a.to?.replaceAll('_',' ')}`}</p>{a.reason&&<p className="retained-text">{a.reason}</p>}</li>)}</ol>:<p>No staff review history is available to this account.</p>}{c.history.length===100&&<p className="muted small">Showing the latest 100 retained events.</p>}</div></section></AppLayout>;
}
