import {router} from '@inertiajs/react';
import {useEffect,useRef,useState} from 'react';
import type {IScannerControls} from '@zxing/browser';
import FieldLayout from '@/Layouts/FieldLayout';
import FormField from '@/Components/Forms/FormField';
import useFieldOnline from '@/hooks/useFieldOnline';
import {scanTarget} from '@/pwa/scanTarget';
export default function Scan({verification_origin}:{verification_origin:string}){
 const video=useRef<HTMLVideoElement>(null),controls=useRef<IScannerControls|null>(null),generation=useRef(0);const [running,setRunning]=useState(false),[error,setError]=useState(''),[value,setValue]=useState(''),[kind,setKind]=useState<'ticket'|'receipt'>('ticket');const online=useFieldOnline();
 const stop=()=>{generation.current++;controls.current?.stop();controls.current=null;if(typeof MediaStream!=='undefined'&&video.current?.srcObject instanceof MediaStream){video.current.srcObject.getTracks().forEach(t=>t.stop());video.current.srcObject=null;}setRunning(false);};
 useEffect(()=>{const preview=video.current,lifecycle=generation;return()=>{lifecycle.current++;controls.current?.stop();if(typeof MediaStream!=='undefined'&&preview?.srcObject instanceof MediaStream)preview.srcObject.getTracks().forEach(t=>t.stop());};},[]);
 const submit=(raw:string,scannedKind:'ticket'|'receipt'=kind)=>{const target=scanTarget(raw,scannedKind,verification_origin);if(!target){setError('Use an OSPM ticket or receipt QR URL, or its 64-character verification code.');return false;}if(!navigator.onLine){setError('Reconnect to verify this code. No offline validity decision is available.');return false;}stop();router.visit(target);return true;};
 const start=async()=>{stop();setError('');if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia){setError('Camera access needs a supported browser on HTTPS or localhost. Enter the verification code below.');return;}const current=++generation.current;setRunning(true);try{const {BrowserQRCodeReader}=await import('@zxing/browser');if(current!==generation.current)return;const reader=new BrowserQRCodeReader(undefined,{delayBetweenScanAttempts:250});const c=await reader.decodeFromConstraints({audio:false,video:{facingMode:{ideal:'environment'}}},video.current!,result=>{if(result&&current===generation.current)submit(result.getText());});if(current!==generation.current)c.stop();else controls.current=c;}catch(e){if(current!==generation.current)return;stop();setError(e instanceof DOMException&&e.name==='NotAllowedError'?'Camera permission was denied. Allow camera access or enter the code below.':'Camera could not start. Check availability and permissions, or enter the code below.');}};
 return <FieldLayout title="Scan QR code"><p className="field-lead">Point the rear camera at an OSPM ticket or receipt QR code.</p><section className="panel"><div className="panel-body"><video className="field-camera" ref={video} muted playsInline aria-label="QR camera preview"/><div className="field-actions"><button className="button" onClick={start} disabled={running||!online}>{running?'Scanning…':'Start camera'}</button><button className="button secondary" onClick={stop} disabled={!running}>Stop camera</button></div><p className="muted small" role="status">{running?'Camera active. Keep the QR code inside the preview.':'Camera is stopped.'}</p>{error&&<p className="field-error" role="alert">{error}</p>}</div></section><section className="panel"><div className="panel-body"><h2>Enter a code instead</h2><form className="payment-form" onSubmit={e=>{e.preventDefault();submit(value);}}><FormField id="scan-kind" label="Record type"><select id="scan-kind" value={kind} onChange={e=>setKind(e.target.value as 'ticket'|'receipt')}><option value="ticket">Ticket</option><option value="receipt">Receipt</option></select></FormField><FormField id="scan-value" label="Verification code or QR URL"><textarea id="scan-value" required maxLength={500} value={value} onChange={e=>setValue(e.target.value)} autoCapitalize="none" autoCorrect="off" spellCheck={false}/></FormField><button className="button" disabled={!online}>Verify code</button></form></div></section></FieldLayout>;
}
