import {Link} from '@inertiajs/react';
import FieldLayout from '@/Layouts/FieldLayout';
import MoneyDisplay from '@/Components/Finance/MoneyDisplay';
import useFieldOnline from '@/hooks/useFieldOnline';
import {dateTime} from '@/lib/formatters';
import type {SafeVerification} from '@/types/field';
export default function VerifyResult({kind,ticket,receipt,checked_at,inspection_url}:{kind:string;ticket:SafeVerification;receipt:SafeVerification|null;checked_at:string;inspection_url:string|null}){
 const online=useFieldOnline(),record=receipt??ticket;
 return <FieldLayout title="Verification result"><section className={'panel field-verdict '+(online&&record.valid?'field-clear':'field-attention')} aria-live="polite"><div className="panel-body"><p className="eyebrow">{kind} check</p><h2>{online?record.result:'Current verification unavailable'}</h2><p>{online?'Checked against the server at '+dateTime(checked_at):'This is a previously loaded record. Reconnect and scan again for a current result.'}</p>{receipt&&<p className="small">Ticket use status: {online?ticket.result:'Requires online check'}. Receipt validity and ticket validity are separate checks.</p>}</div></section><section className="panel"><div className="panel-body"><h2>Record details</h2><dl className="field-facts">{receipt&&<><dt>Receipt</dt><dd>{receipt.receipt_number}</dd><dt>Payment reference</dt><dd>{receipt.payment_reference}</dd></>}<dt>Ticket</dt><dd>{ticket.ticket_reference}</dd><dt>Vehicle</dt><dd>{ticket.vehicle??'Not recorded'}</dd><dt>Park</dt><dd>{ticket.park??'Not recorded'}</dd><dt>Revenue item</dt><dd>{ticket.fee_name}</dd><dt>Original amount</dt><dd><MoneyDisplay amount={record.amount} currency={record.currency}/></dd><dt>Ticket status</dt><dd>{ticket.ticket_status}</dd><dt>Payment status</dt><dd>{record.payment_status}</dd><dt>Issued</dt><dd>{dateTime(record.issued_at)}</dd><dt>Ticket expires</dt><dd>{ticket.expires_at?dateTime(ticket.expires_at):'No expiry recorded'}</dd></dl><p className="muted small">Original amounts are retained after corrections. The current server result determines validity.</p></div></section><div className="field-actions"><Link className="button" href="/field/scan">Scan again</Link>{inspection_url&&<Link className="button secondary" href={inspection_url}>Record inspection</Link>}</div></FieldLayout>;
}
