import {Head,Link,router,usePage} from '@inertiajs/react';
import {useEffect,useState,type ReactNode} from 'react';
import {Home,ScanLine,Search,ClipboardCheck,LogOut} from 'lucide-react';
import Brand from '@/Components/App/Brand';
import Toast from '@/Components/Feedback/Toast';
import {LoadingState,ErrorState} from '@/Components/Feedback/States';
import useBrandTokens from '@/hooks/useBrandTokens';
import useFieldOnline from '@/hooks/useFieldOnline';
import type {SharedProps} from '@/types';
type InstallEvent=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>};
export default function FieldLayout({title,children}:{title:string;children:ReactNode}){
 const style=useBrandTokens(),online=useFieldOnline();const {auth,system}=usePage<SharedProps>().props;const [install,setInstall]=useState<InstallEvent|null>(null);const [loading,setLoading]=useState(false),[networkError,setNetworkError]=useState(false);const [pwaError,setPwaError]=useState(false);
 useEffect(()=>{const prompt=(e:Event)=>{e.preventDefault();setInstall(e as InstallEvent);};const installed=()=>setInstall(null);window.addEventListener('beforeinstallprompt',prompt);window.addEventListener('appinstalled',installed);if('serviceWorker' in navigator&&window.isSecureContext)navigator.serviceWorker.register('/field/sw.js',{scope:'/field/',updateViaCache:'none'}).catch(()=>setPwaError(true));return()=>{window.removeEventListener('beforeinstallprompt',prompt);window.removeEventListener('appinstalled',installed);};},[]);
 useEffect(()=>{const start=router.on('start',()=>{setLoading(true);setNetworkError(false);});const finish=router.on('finish',()=>setLoading(false));const exception=router.on('exception',e=>{e.preventDefault();setLoading(false);setNetworkError(true);});const before=router.on('before',e=>{if(!navigator.onLine){e.preventDefault();setNetworkError(true);}});return()=>{start();finish();exception();before();};},[]);
 const nav=[{label:'Home',href:'/field/',Icon:Home,permission:'access_field'},{label:'Scan',href:'/field/scan',Icon:ScanLine,permission:'verify_ticket'},{label:'Look up',href:'/field/vehicles',Icon:Search,permission:'field_lookup'},{label:'Inspect',href:'/field/inspections/create',Icon:ClipboardCheck,permission:'record_inspection'}];
 return <div className="field-app" style={style}><Head title={title}><link rel="manifest" href="/pwa-field/manifest.webmanifest"/><link rel="apple-touch-icon" href="/pwa-field/icons/icon-192.png"/><meta name="apple-mobile-web-app-capable" content="yes"/><meta name="apple-mobile-web-app-title" content="OSPM Field"/></Head><a className="skip-link" href="#field-main">Skip to field content</a><header className="field-header"><Link href="/field/" title="Field home"><Brand compact/></Link><Link href="/logout" method="post" as="button" className="icon-button" aria-label="Sign out"><LogOut size={21}/></Link></header><main id="field-main" className="field-main"><div className="field-intro"><span className="eyebrow">Enforcement workspace</span><span className={'field-connection '+(online?'':'offline')} role="status">{online?'Online':'Offline'}</span></div><h1>{title}</h1>{system.demo_mode&&<p className="field-demo">Demonstration · Synthetic data only</p>}<Toast/>{!online&&<p className="notice" role="alert"><strong>Current checks unavailable offline.</strong> Previously loaded data may be stale. Reconnect before searching, verifying or saving. Nothing is queued offline.</p>}{loading&&<LoadingState label="Updating field view…"/>}{networkError&&online&&<ErrorState message="Connection interrupted. Retry this form with the same details to recover a possible saved result."/>}<div className="field-content">{children}</div><section className="field-install"><strong>Keep the field app close</strong>{install?<button className="button secondary" onClick={async()=>{await install.prompt();await install.userChoice;setInstall(null);}}>Install field app</button>:<p className="muted small">Use your browser’s Install app or Add to Home Screen option where supported.</p>}{pwaError&&<p className="small">Offline shell is unavailable. Online field tools remain usable.</p>}</section><footer className="field-footer"><span>{auth.user?.name}</span><Link className="text-link" href="/account/access">My access</Link><small>{system.branding.powered_by}</small></footer></main><nav className="field-bottom-nav" aria-label="Field navigation">{nav.filter(n=>auth.permissions.includes(n.permission)).map(({label,href,Icon})=><Link key={href} href={href}><Icon size={21} aria-hidden="true"/><span>{label}</span></Link>)}</nav></div>;
}
